# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
