# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='option2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='option1',
            field=models.BooleanField(default=False),
        ),
    ]
