# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20180323_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
