# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20180327_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='colorp',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
